### ISSUE TITLE
Flag inappropriate discussion

### ISSUE THREAD

**Issue by jordanjay29** [flagrow/byobu#2] opened 2017-01-25 09:18 UTC
The user needs the ability to flag a private discussion where something is going wrong. 
Admins/mods/groups with the appropriate permissions need to be able to see the private discussion when flagged.
The above groups need a way to exit the private discussion when the flagged incident has been resolved so the privacy can be restored if possible (controllable by the flagging user as well so admins cannot snoop).

**Comment by Luceos** [comment] 2017-01-26 15:31
Showing a tooltip on PD's which users/group have access, in case admins can read along?

**Comment by jordanjay29** [comment] 2017-01-26 16:03
Maybe only visible to the user flagging it? Thinking about times where users are reporting harassment, and where giving the harasser the knowledge they're being reported only makes it worse.

**Comment by Luceos** [comment] 2017-01-26 19:30
Or perhaps simply only show the flagged post(s) in the discussion and obscure the rest.. 💭

**Comment by Luceos** [comment] 2017-02-21 15:30
The issue is like this;

The core discussion policy uses the following query:

```php
        if ($actor->cannot('viewDiscussions')) {
            $query->whereRaw('FALSE');
        } elseif (! $actor->hasPermission('discussion.hide')) {
            $query->where(function ($query) use ($actor) {
                $query->whereNull('discussions.hide_time')
                    ->where('comments_count', '>', 0)
                    ->orWhere('start_user_id', $actor->id);

                $this->events->fire(
                    new ScopeHiddenDiscussionVisibility($query, $actor, 'discussion.hide')
                );
            });
        }
```

During the `ScopeHiddenDiscussionVisibility` Byobu adds another where:

```php
        $query->where(function (EloquentBuilder $query) use ($actor) {
            $query->whereNotExists(function (Builder $query) {
                $query->select(app('flarum.db')->raw(1))
                    ->from('recipients')
                    ->where('discussions.id', new Expression('discussion_id'))
                    ->whereNull('removed_at');
            });
            if ($actor->exists) {
                $query->orWhereExists(function (Builder $query) use ($actor) {
                    $query->select(app('flarum.db')->raw(1))
                        ->from('recipients')
                        ->where('discussions.id', new Expression('discussion_id'))
                        ->whereNull('removed_at')
                        ->where(function (Builder $query) use ($actor) {
                            $query->where('recipients.user_id', $actor->id);
                            if (!$actor->groups->isEmpty()) {
                                $query->orWhereIn('recipients.group_id', $actor->groups->pluck('id')->all());
                            }
                        });
                });
            }
        });

        if ($actor->exists) {
            $this->showWithFlags($query, $actor, 'posts.flags');
        }
```

The show with flags, allows viewing discussions with flags in case you have the permission.

In this situation the where from core will prevent viewing the discussion because it has a `comments_count` of 0, indicating it has no publicly visible posts/comments.

So we should use an or, but using an or sets all concurrent where's after the OR and thus opening up all discussions under any tag to everyone.

**Comment by tobscure** [comment] 2017-02-27 08:52
@Luceos hmm so what do we need to change in core to fix this?

**Comment by Luceos** [comment] 2017-02-27 09:00
@tobscure the queries are conflicting, especially if you include the Flags extension. The Flags extension is doing an `orWhere`, any code that follows will not be able to limit the result set anymore. Even modifying the `wheres` array in the `Builder` instance is not a guaranteed solution, because in my use case the Flags extension `orWhere` was added after mine.

Perhaps we need to fire an event when an extension updates the scope. Thus I could hook into the event fired when the Flags extension is running it's query and add my query afterwards.

**Comment by Luceos** [comment] 2017-02-27 10:18
Log of work:

- setting `orWhere` allows non-admin to see PD of which he is recipient

**Comment by tobscure** [comment] 2017-02-27 11:07
@luceos sorry if I'm approaching this naively (permissions are always hard to reason about) but why are you listening to ScopeHiddenDiscussionVisibility at all? Shouldn't you just be registering a new DiscussionPolicy and applying conditions in the `find` method?

**Comment by Luceos** [comment] 2017-02-27 11:19
@tobscure no problem of being observant. Thanks for looking into this and questioning my decisions.

I'm actually implementing a find, that's exactly what this is about. I see in previous comments I said Flags extension, but I meant Tags. So ..

What happens is the following, we start out with:

```php
    if ($actor->cannot('viewDiscussions')) {
            $query->whereRaw('FALSE');
        } elseif (! $actor->hasPermission('discussion.hide')) {
            $query->where(function ($query) use ($actor) {
                $query->whereNull('discussions.hide_time')
                    ->where('comments_count', '>', 0)
                    ->orWhere('start_user_id', $actor->id);

                $this->events->fire(
                    new ScopeHiddenDiscussionVisibility($query, $actor, 'discussion.hide')
                );
            });
        }
```

The `ScopeHiddenDiscussionVisibility` allows modification of this, quite properly too. The tags extension adds the following:

```php
        // Hide discussions which have tags that the user is not allowed to see.
        $query->whereNotExists(function ($query) use ($actor) {
            return $query->select(new Expression(1))
                ->from('discussions_tags')
                ->whereIn('tag_id', Tag::getIdsWhereCannot($actor, 'viewDiscussions'))
                ->where('discussions.id', new Expression('discussion_id'));
        });

        // Hide discussions with no tags if the user doesn't have that global
        // permission.
        if (! $actor->hasPermission('viewDiscussions')) {
            $query->has('tags');
        }
```

So the combined query creates an `AND`. Very good.

> "the Actor can see the discussions he can hide AND those with tags he can view discussions in"

Now my Byobu wants to open up discussions to users that are recipients. If I add an `AND` the conclusion of the query will be:

> "the Actor can see the discussions he can hide AND those with tags he can view discussions in AND where he is an recipient of"

Which closes it down too much. Using an OR:

> "the Actor can see the discussions he can hide AND those with tags he can view discussions in OR where he is an recipient of"

Cancels the effect of the Tags extension. A solution in pure Eloquent terminology would be to use Grouping, Sub querying. But that's quite hard to achieve in the current situation. 

I'm now in the process to mutate the Query at the end, when all others are done. And rebuild the whole Query anew with grouping.

**Comment by Luceos** [comment] 2017-02-27 13:25
@tobscure so I was backtracing the steps in this issue. I've written down the [query above](https://github.com/flagrow/byobu/issues/2#issuecomment-282680934).

Something that blocks this is that `comment_count` on the discussion table is an integer that indicates the number of posts visible to the public. Due to the fact that this query is included as an `AND` any private/non-public discussions will be invisible by default.

**Comment by Luceos** [comment] 2017-02-27 14:19
Tried implementing the exact behavior the tags extension does. Ran into the issue that the tags extension sets an `AND` where in the `scopeHiddenDiscussionVisibility` which reduces the list to leave out private discussions.

**Comment by Luceos** [comment] 2017-02-27 14:33
I think I fixed it!

**Comment by Luceos** [comment] 2017-02-27 14:34
`find` and `scopeHiddenDiscussionVisibility` are able to inject mysql at different positions

**Closed** 2017-02-28 08:36 UTC
Labels: enhancement
